language: csharp
solution: src/Saturn72.Extensions.sln
mono: none
dotnet: 2.1.3

script:
 - cd src
 - dotnet restore Saturn72.FileConverters.sln
 - dotnet build Saturn72.FileConverters.sln
  # test
 - dotnet test Saturn72.FileConverters.Tests/Saturn72.FileConverters.Tests.csproj
